### ISSUE TITLE
Can not configure path to the tools on Windows

### ISSUE THREAD

**Issue by alexbruy** [volaya/qgis-lidartools-plugin#1]
When I try to run any LiDAR algorithm a message saying "LAStools folder not configured. Please configure it before running LAStools algorithms" shown.

But when I try to set folder in Processing->Options->Providers->Tools for LiDAR data->LAStools folder, there is no "Value" field at all. There is no way I can set it. Neither can I set the Fusion folder even though the Activate button is checked. QGIS 2.18.3 on Windows 7.

Moved from QGIS bugtracker https://issues.qgis.org/issues/16126

**Comment by rapidlasso** [comment]
Old bug from QGIS 2.18.3. User error? Not meaningful for QGIS 3.2 port.
